name: 'Infrastructure & Pipeline Deploy'

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '.gitignore'
      - 'README.md'
      - 'requirements.*'
      - 'LICENSE'
  workflow_dispatch:

jobs:
  terraform-and-dataflow:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Create GCP Service Account Key File
      run: |
        echo '${{ secrets.GCP_SA_KEY }}' > ${{ github.workspace }}/gcp_key.json

    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_wrapper: false

    - name: Terraform Init & Apply
      id: terraform_step
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp_key.json
      run: |
        cd infra
        terraform init
        terraform apply -auto-approve
        echo "project_id=$(terraform output -raw project_id)" >> $GITHUB_OUTPUT
        echo "bucket_url=$(terraform output -raw staging_bucket_url)" >> $GITHUB_OUTPUT
        cd ..

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Launch Dataflow Pipeline
      env:
        PROJECT_ID: ${{ steps.terraform_step.outputs.project_id }}
        BUCKET_URL: ${{ steps.terraform_step.outputs.bucket_url }}
        GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp_key.json
      run: |
        python src/pipeline.py \
          --runner DataflowRunner \
          --project $PROJECT_ID \
          --region us-south1 \
          --staging_location $BUCKET_URL/staging \
          --temp_location $BUCKET_URL/temp \
          --job_name airline-segmentation-gh-$(date +%s) \
          --streaming \
          --service_account_email=infra-deployer@data-stream-passengers.iam.gserviceaccount.com
